### PR TITLE
RSA keys from existing secret

### PR DESCRIPTION
**Pull request by drustan**
The goal is to implement the ability to retrieve the RSA keys from an existing secret

### CODE REVIEW

**Comment by drustan** [comment]
Hi! Is there any reason this is not reviewed / accepted?

**Review by arikalon1 — APPROVED** [review]
Sorry for the late reply @drustan 
Thanks for your contribution

**Comment by jmalloc** [comment]
Any chance of a new tag that includes these changes? It took me a while to work out why this wasn't working, because the documentation for it is already live :wink:

**Comment by arikalon1** [comment]
You're right @jmalloc 
The docs contains the change, but it wasn't released yet.
It will be included in 0.10.26
It should be released within a week or so

**Pull request merged**
