### PR TITLE
Added 'Edit this page on Github'

### LINKED ISSUE #196: Add an edit on GitHub button to each page in the docs
Goal is to make it easier for people to submit contribution to the docs. Many people don't understand today that the docs are open source.

Thank you to @Sayanta66 for the idea!

### PR DESCRIPTION
**Pull request by kandahk**
Part of fix #196. This is my first contribution to any Open Source project. So pardon any ignorance.

### CODE REVIEW

**Comment by aantn** [comment]
Hi, thanks for submitting! I think we need a way to add this to every single page at once.

I don't have a reference on hand for this, but I've seen Sphinx themes before that do this. We're using the Furo theme so we'll need a plugin/method which is compatible with Furo: https://pradyunsg.me/furo/quickstart/

**Comment by kandahk** [comment]
Hello,
How about using rst_epilog ?
https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_epilog

**Comment by aantn** [comment]
Is there a way to make that dynamic so it opens github on the docs page you're currently viewing and not just the docs in general?

Maybe something like this? https://gist.github.com/mgedmin/6052926

I really like the way that the RTD Theme for Sphinx handles this ([see the "Edit on GitHub" link here](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html))

**Comment by aantn** [comment]
There is apparantly some discussion about this over for the Furo theme: https://github.com/pradyunsg/furo/discussions/114

Maybe it's worth pinging them there and seeing what the status is.

**Comment by kandahk** [comment]
OK, I have asked to furo, let's see what they come back with.

**Comment by aantn** [comment]
Cool, thanks :)

**Comment by aantn** [comment]
Nice catch. It seems to be only for docs hosted on Read the Docs. Any idea what we'd have to do to adapt it for us? (We're hosting the docs ourselves, not with Read the Docs.)

**Comment by aantn** [comment]
Hi, I'm closing this PR.

Please feel free to open a new PR in the future. A solution that adds the edit button for all pages would be great!

Thank you for spending some of your time on Robusta! If you're at Kubecon, please come by the booth and we would love to give you swag.

**Pull request closed without merging**
