### PR TITLE
gcloud option

### PR DESCRIPTION
**Pull request by Avi-Robusta**

### CODE REVIEW

**Comment by Avi-Robusta** [comment]
skaffold run -p gcloud-build

**Comment by arikalon1** [comment]
LGTM

**Comment by aantn** [comment]
@Avi-Robusta can you add a sentence to the docs here: https://docs.robusta.dev/master/developer-guide/platform/dev-setup.html#installing-robusta-in-cluster-from-source

e.g. "You can use `skaffold run -p gcloud-build` for faster builds"

Then go ahead and merge?

**Comment by aantn** [comment]
Awesome, merged and deleted the branch.

Thanks, Avi!

**Pull request merged**
