### PR TITLE
feat(helm): update kube-prometheus-stack to 47.2.0

### PR DESCRIPTION
**Pull request by lippertmarkus**

### CODE REVIEW

**Comment by lippertmarkus** [comment]
@RoiGlinik could you please review? :)

**Comment by RoiGlinik** [comment]
Hey @lippertmarkus , I will look into it next week, as it does require some upgrade instructions on our docs. ( because of the crds and other possible changes. ) 

Was there any particular fix they added in this version that your interested in ?

**Comment by lippertmarkus** [comment]
I'm especially interested in https://github.com/prometheus-community/helm-charts/pull/3083

Can I help you with upgrade instructions? Just putting the ones from https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack#upgrading-an-existing-release-to-a-new-major-version into upgrade.rst?

**Comment by RoiGlinik** [comment]
Yea, this could speed up the process a bit, we have a section about it on our docs.
https://docs.robusta.dev/master/setup-robusta/upgrade.html#why-are-manual-upgrades-necessary

Every kube-prom-stack upgrade on our chart creates friction for users, so we tend to be careful with that.

I will have to test the upgrade scenario myself

**Comment by lippertmarkus** [comment]
i updated the upgrade docs (kept the removal of node-exporter  and webhooks for people upgrading from 0.10.8 to 0.10.18+)

**Comment by RoiGlinik** [comment]
@lippertmarkus Did not forget, had a problemtic schedule this week. Will review soon

**Comment by lippertmarkus** [comment]
@RoiGlinik thanks! can we do a new release of the Robusta chart as well?

**Comment by tfenster** [comment]
@RoiGlinik Any ideas when this might be released? Would be very helpful for us as well

**Comment by arikalon1** [comment]
We're releasing it this week @tfenster

**Pull request merged**
