### PR TITLE
add promtheus labels to slack message

### PR DESCRIPTION
**Pull request by romga**

### CODE REVIEW

**Review by arikalon1 — APPROVED** [review]
LGTM

**Comment by wrbbz** [comment]
But why?

**Comment by romga** [comment]
> But why?

can you please elaborate?

**Comment by wrbbz** [comment]
What for do we need prom labels in slack message? As I think, it is a little bit excessive information. Am I wrong?

**Comment by romga** [comment]
@wrbbz 
i am using the labels in order to decide which alert sent to which channel :)

**Comment by wrbbz** [comment]
Why not use kubernetes labels?

Nevertheless, they will be shown in aggregation key

On the other hand, I would suggest more dynamic message creation. If there are some labels - we add labels in the message, if none - no mention at all (instead of `None`). It could be misleading. I would have decided, that there is an issue with some data absence if I see `None`

**Pull request merged**
