### PR TITLE
Updated "values.yaml" to "generated_values.yaml"

### PR DESCRIPTION
**Pull request by pavangudiwada**
- Updated almost all instances of "values.yaml" to "generated_values.yaml"
-  Added upgrade options to some sinks.

### CODE REVIEW

**Comment by RoiGlinik** [comment]
Hey, @pavangudiwada it looks good. Need to add "cb-" prefix to code blocks for the analytics.
for example:
add-victorops-sink -> cb-add-victorops-sink 


also, what's the advantage of using a fork? just curious

**Review by RoiGlinik — APPROVED** [review]
Hey, @pavangudiwada it looks good. Need to add "cb-" prefix to code blocks for the analytics.
for example:
add-victorops-sink -> cb-add-victorops-sink

also, what's the advantage of using a fork? just curious

**Comment by pavangudiwada** [comment]
Add the prefix "cb-" for all the sinks. 
@RoiGlinik What **Forks** do you mean?

**Comment by pavangudiwada** [comment]
Oh, yea. Just helps me experiment without messing up things. But isn't that how everyone works? :thinking:

**Review by RoiGlinik — APPROVED** [review]

**Pull request merged**
