### PR TITLE
Fixed table of contents

### PR DESCRIPTION
**Pull request by pavangudiwada**

### CODE REVIEW

**Comment by aantn** [comment]
Weird, it's still not working for me. I tested via https://github.com/robusta-dev/robusta/blob/a7274551e34d2312cb84681a09b4be9da77bd47f/README.md#%F0%9F%93%92-installing-robusta

I click on links in the table of contents, but I don't jump to the new location.

**Comment by pavangudiwada** [comment]
> Weird, it's still not working for me. I tested via https://github.com/robusta-dev/robusta/blob/a7274551e34d2312cb84681a09b4be9da77bd47f/README.md#%F0%9F%93%92-installing-robusta
> 
> I click on links in the table of contents, but I don't jump to the new location.

We'll yea, it worked locally and the "emojies" are messing up, guess that's why I did not add them in the first place when I changed the README. 

Here is a slightly modified version, except "How it works” and "Contacts" the others are working. Not sure why. https://github.com/robusta-dev/robusta/blob/readmefixtest/README.md#-installing-robusta. Let me know how to proceed.

**Comment by aantn** [comment]
Can we just get rid of the table of contents then? Better to leave it out then have something broken.

**Comment by pavangudiwada** [comment]
Yes, let's take it out. Looks like GitHub gives you a ToC by default. Closing this issues, will create a new PR. 
image

**Pull request closed without merging**
