### PR TITLE
Updating free videos link

### PR DESCRIPTION
**Pull request by sassukeuchiha**
Earlier the videos link redirected to https://home.robusta.dev/learning which gave a 404 updated it to https://home.robusta.dev/videos

### CODE REVIEW

**Review by arikalon1 — APPROVED** [review]
Looks good
Thanks for your contribution

**Comment by sassukeuchiha** [comment]
Thank You for accepting my PR :)
will look out further for good first issues.

**Comment by arikalon1** [comment]
Can you please sign the CLA @sassukeuchiha so we can merge it  ?

**Comment by sassukeuchiha** [comment]
Done 👍

**Pull request merged**
